name: MSTR_Admin
main: ca.strendin.MSTR_Admin.MSTR_Admin
version: 1
author: Mark Strendin
description: Basic admin enhancements
permissions:
  strendinadmin.sethome:
   description: Able to set a home point without using a bed
   default: op
  strendinadmin.setspawn:
   description: Able to set the spawn point for the current world
   default: op
  strendinadmin.kick:
   description: Able to kick players from the server
   default: op
  strendinadmin.ban:
   description: Able to ban players from the server
   default: op
  strendinadmin.info:
   description: Able to get information from players, including health and hunger
   default: op
  strendinadmin.teleport:
   description: Able to teleport
   default: op
  strendinadmin.time:
   description: Able to set day and night
   default: op  
  strendinadmin.grant:
   desription: Able to grant levels to players
   default: op
  strendinadmin.spawn:
   description: Able to teleport to the spawn point
   default: op
  strendinadmin.home:
   description: Able to teleport to the home point
   default: op
  strendinadmin.vanish:
   description: Able to vanish
   default: op
  strendinadmin.commandblock:
   description: Able to create a command block
   default: op
commands:  
  commandblock:
    description: Summons a command block without needing to know the block ID
    permission: strendinadmin.commandblock       
  sethome:
    description: Sets your home / respawn location
    permission: strendinadmin.sethome
  setspawn:
    description: Sets the world's spawn location
    permission: strendinadmin.setspawn
  spawn:
    description: Teleports to the world's spawn location
  playerinfo:
    aliases: [pi,whois,info]
    description: Displays player information for the specified player
    permission: strendinadmin.info
  bring:
    aliases: [b]
    description: Teleports selected player to the caster
    permission: strendinadmin.teleport
  day:
    description: Sets the current world's time to day
    permission: strendinadmin.time
  night:
    description: Sets the current world's time to night
    permission: strendinadmin.time  
  grant:
    aliases: [level,givelevel,grantlevel]
    description: Grants the specified player a level
    permission: strendinadmin.grant
  home:
    description: Returns the player to their home point (where they last slept in a bed)
    permission: strendinadmin.home
  vanish:
    description: Gives the player the effects of a vanish potion
    permission: strendinadmin.vanish
  test:
    description: Just a test command